### ISSUE TITLE
game.Camera, choppy animation when following

### ISSUE THREAD

**Issue by nvaken** [ekelokorpi/panda.js-engine#106]
When following a sprite, the sprite seems to be a bit choppy. Just a 1 or 2 px glitch a few times a second. Could be a rounding problem? Or it might have something to do with my issue that I just created, I'm using the scene's update function to trigger the update function of the camera.

**Comment by nvaken** [comment]
@ekelokorpi, I'm noticing you're having a big cleanup lately. Any feedback on the denial of the above?

**Comment by ekelokorpi** [comment]
Yeah big changes coming, next version will be 2.0.
I will take a new look at the Camera class at some point.
