### ISSUE TITLE
Spine animation isn't working with 1.13 PandaJS

### ISSUE THREAD

**Issue by SergeySuslov** [ekelokorpi/panda.js-engine#127]
Hello,

I can't run spine animation with new 1.13 PandaJS where Pixi 2.2.5 is supported. I got error "Uncaught Animation not found: true" which was thrown by setAnimationByName function
```javascript
setAnimationByName: function (trackIndex, animationName, loop) {
        var animation = this.data.skeletonData.findAnimation(animationName);
        if (!animation) throw "Animation not found: " + animationName;
        return this.setAnimation(trackIndex, animation, loop);
    }
```
There is some new parameter trackIndex which doesn't exist in the render.js file:
```javascript
game.Spine.prototype.play = function(anim, loop, after) {
    if (after) this.state.addAnimationByName(anim, !!loop);
    else this.state.setAnimationByName(anim, !!loop);
};
```
I don't understand what this new trackIndex means and what value I shoud set it. Could you help?

**Comment by ekelokorpi** [comment]
Hi!

You are right, there has been some change with Spine on Pixi.
I will try to look at that asap to get it fixed on Panda.

Thanks!

**Comment by ekelokorpi** [comment]
This will be fixed on Panda v2, that is the next version.
Actually i'm planning to add Spine support as a plugin.
