### ISSUE TITLE
Allow mousemove event to be used outside scene

### ISSUE THREAD

**Issue by nvaken** [ekelokorpi/panda.js-engine#128]
Might be a nice idea to add support for other instances to add themselves to the Panda.js native mousemove events. Now the only way I see fit is to add your scene and use it's `mousemove()` method to fire other mousemove functions. Might this be a good addition to be added to objects that have been added with `addObject()`? Something like this would be awesome:

```
game.module(
    'game.main'
)
.body(function() {

game.createClass('SomeClass', {
    mousemove: function () {
         // This will be triggered because of the addObject later on
    }
});
game.createScene('Main', {
    backgroundColor: 0xb9bec7,

    init: function() {
         var instance = new game.SomeClass();
         this.addObject(instance);
    }
});
});
```

**Comment by pixelpicosean** [comment]
Can't you just set `DisplayObjects.interactive` to `true` and listen to `mousemove` event fired by them? I don't see any benefits of making every object interactive since they may not represent something visual.

**Comment by nvaken** [comment]
I'm not familiar with that approach, do you have any sample code for this? I'm not really sure how I would implement this on a basic class as seen in the sample above?

**Comment by ekelokorpi** [comment]
Interactivity is handled by Pixi, take a look at this example:
http://www.goodboydigital.com/pixijs/examples/6/

**Comment by nvaken** [comment]
So, you'll need to use a Sprite for getting interactivity. But what if I would want a custom class, which I need to be independent from the main scene (only to be added by instantiation and to setup some simple properties), to receive mousemove / mouseout, etc...? I'm talking about a factory class mainly here. What would the best approach be from there?

**Comment by ekelokorpi** [comment]
I would redirect mouse event from scene to the class.

	mousemove: function(event) {
		this.myClass.mousemove(event);
	}

**Comment by nvaken** [comment]
Yeah, that has been my solution until now, I just wondered how you might go about making this a bit more robust. Hearing about the `interactive` approach, I would almost consider a functionality something like the following:

```
...
game.createScene('Main', {
    backgroundColor: 0xb9bec7,

    init: function() {
         var instance = new game.SomeClass();
         this.setInteractive(instance);
    }
});
...
```

Not entirely what I originally meant, but I think this would already prevent a lot of clutter and storing logic in places where you might not actually be sure of the existence of the object which would require conditionals to check if the object is already instantiated.

**Comment by ekelokorpi** [comment]
this.setInteractive(instance);

If i understood correctly, that would need `for` loops in every mouse event function to go through every interactive class, and then check if it got that mouse function to call.

**Comment by nvaken** [comment]
Hm... you're right, that sounds totally bloated. I guess the current way, is probably the way to go.

**Comment by ekelokorpi** [comment]
Well it has been for me so far, usually if i got game with fullscreen controls, i'm redirecting scene's mouse events to one class, usually Player, so that's not many lines of code. Can't think of a situation, where i would need to redirect into lots of different classes..

**Comment by nvaken** [comment]
Yeah, I think I'd better rethink a bit of my logic in my current app. What you're saying makes a lot of sense. Thanks for the help!
