### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by da1nonly** [ekelokorpi/panda.js-engine#131]
I don't know if this is the right place to add this, but have you come across mightyfingers game editor, looks pretty cool , would be good to have something for panda.js , its based of Phaser.io . 
 
http://mightyfingers.com/editor-features/
https://github.com/TheMightyFingers/mightyeditor

**Comment by pixelpicosean** [comment]
There's one called [bamboo](https://github.com/ekelokorpi/panda.js-bamboo) made for Panda but is not finished yet. You have to wait for a while since Enpu is working on engine 2.0, editor, launcher and new website recently. That's really lots of work.
