### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by ekelokorpi** [ekelokorpi/panda.js-engine#152]

**Comment by goide** [comment]
What is the error that is having the Class "Camera" in this version?

**Comment by goide** [comment]
From what I've written in the forum, these are the mistakes that I could see.

1. No recognizes the stage as an overall container.
2. No follows the object when you are directed to a negative position in x, and a negative position in y.
3. Do an example with the camera and bodies. and it was not working properly, if you want I can show you a video of how this operation.

Another question, the camera on the stable version, if you can follow a sprite. that for this version to follow you put a container. it would not be better to continue following a sprite.
