### ISSUE TITLE
Should the prevention of touchstart be more flexible?

### ISSUE THREAD

**Issue by nvaken** [ekelokorpi/panda.js-engine#153]
I'm working on an app which will use the Panda JS canvas and some DOM interface on top of it. Currently on mobile devices the `mousestart` `preventDefault()` blocks all my touches on e.g. links. Should the element on which this event is applied be configurable, with a default value for the `document`? I currently patched my system.js where I replaced `document` with `this.canvas` which works perfectly.

**Comment by ekelokorpi** [comment]
This should be fixed on 2.0
