### ISSUE TITLE
click event registered outside of the stage

### ISSUE THREAD

**Issue by EranGilo** [ekelokorpi/panda.js-engine#154]
In the develop branch when you have a large clickable sprite expanding outside of the stage bounds it remains clickable outside of the stage.

**Comment by ekelokorpi** [comment]
Can you give me a working example

**Comment by EranGilo** [comment]
Ok I found out it happens only with the mouseup event.
I uploaded a working example of this issue. you can find it here:
https://www.dropbox.com/sh/5mokdcn2f4xz2tn/AADv9WLqbQxlrAhaDmRLJ85ba?dl=0

load the index and click outside of the stage on it's right side or bottom side (where the background image is supposed to be but is clipped inside).

**Comment by ekelokorpi** [comment]
This has been fixed now, thanks!
