### ISSUE TITLE
event.stopPropagation

### ISSUE THREAD

**Issue by EranGilo** [ekelokorpi/panda.js-engine#155]
I wanted to ask how come panda events does not support the stopping of propagation and bubbling? It is very useful to be able to limit bubbling.

I assume that to implement it I need to look inside **input.js** in the **_processEvent** function and break the loop if the item has a **stopPropagation** property set to true or something like that. What would be the best solution in your opinion? do you know how to browser natively does that with the **event.stopPropagation()** call? maybe that calls a prototype function that sets some property of event that is being checked I don't know...

**Comment by ekelokorpi** [comment]
Just to clarify, you want to call event (i.e. mousedown) on object, but not on objects below it?
You can return true on your event function to skip all next objects.

**Comment by EranGilo** [comment]
I am trying to do exactly what you described but your example doesn't create the wanted result.

paste this in **http://ekelokorpi.github.io/panda.js-site/engine/playground/#input_sprite**

```javascript
game.addAsset('panda.png');

game.createClass('Panda', 'Sprite', {
	texture: 'panda.png',
	interactive: true,

	init: function(x, y) {
		this.position.set(x, y);
		this.addTo(game.scene.stage);
	},

	mousedown: function() {
// 		this.remove();
        this.alpha = 0.5;
	},

	mousemove: function() {
		
	},

	mouseout: function() {
		this.alpha = 1;
	}
});

game.createClass('Dot', 'Graphics', {
	interactive: true,
	dotWidth: 20,
	dotHeight: 20,

	init: function(x, y) {
		this.position.set(x - this.dotWidth/2,y - this.dotHeight/2);
		this.lineStyle(1,'#000000',0.4);
		this.beginFill('#17c743',1);
		this.drawCircle(10,10,10);
		this.addTo(this);
		this.addTo(game.scene.stage);
	},

	mousedown: function() {
// 		this.remove();
        this.alpha = 0.5;
        return true;
	},

	mousemove: function() {
		
	},

	mouseout: function() {
		this.alpha = 1;
	}
});

game.createScene('Main', {
	init: function() {
		var sprite = new game.Panda(100, 100);
		var dot = new game.Dot(120,120);
	}
});
```

**Comment by ekelokorpi** [comment]
Ah sorry! It was just the opposite, if you return true on event function, engine will continue to call events on other items also.

**Comment by EranGilo** [comment]
But the engine does it either way if you return true and if you return nothing it still bubbles up.

**Comment by ekelokorpi** [comment]
Are you sure? I just tested and it seems to be working as expected.

**Comment by EranGilo** [comment]
That is so weird... in the example above if I remove the return true it doesn't bubble up and in an isolated example I created locally it doesn't bubble up either but in my actual game it does.... I am lost.

**Comment by EranGilo** [comment]
OK I came to the conclusion that the issue I saw in my game was due to me adding the smaller sprites as childrens of the bigger sprite. I placed them all in a container instead and it solved it. I don't know this is intended behavior or not but at least I found a fix for now.
