### ISSUE TITLE
Graphics arc

### ISSUE THREAD

**Issue by LinkTree3** [ekelokorpi/panda.js-engine#157]
Hi I wanted to ask how come arcs have been removed from the develop branch of panda? they are very useful in creating pie charts and circular timers. I would try to add it myself but I am not sure how to go about doing this while maintaining support for canvas and webGL at the same time.

**Edit**: Ok I just realized you removed the whole webGL side of the renderer and are planning on releasing it as a plugin in the future. This makes it a lot simpler to add the graphics arc shape myself I guess.

**Comment by ekelokorpi** [comment]
You are right, that should be added to 2.0

**Comment by EranGilo** [comment]
I had already added it in my own version if you want I can merge it.
I also added a spriteTinter class based on pixi’s canvasTinter class. currently I have it set as a separate plugin that adds the spriteTinter class and inject necessary changes into game.Sprite.

**Comment by ekelokorpi** [comment]
That would be great if you can make pull request.
I think tinter can be as a plugin for now.

**Comment by EranGilo** [comment]
I am in the process of cleaning up the code for release. In my version I added support for linear and radial gradients on shapes do you want it as well?
